### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by oleksandr-jr** [OnDecember/JavaRush-Projects#1]
I would like to express my evaluation of the project based on some important aspects:

The support for two languages is an additional advantage of this project. It is implemented well and allows for effective language detection.

The language detection mechanism works satisfactorily. It is capable of correctly identifying the language of the text with high accuracy.

The use of an enumeration type (`enum`) to represent languages is a rational approach. It helps maintain understandable and easily modifiable code.

The cryptographic brute-force algorithm (method `bruteForce()`) using regular expressions is an extraordinary solution that functions effectively. However, it should be noted that this approach may malfunction when adding new languages with different alphabets.

The nested for loop with three levels of nesting is not an optimal solution. There is room for improvement in this algorithm to avoid such a level of nesting. Additionally, it is unclear why the loop condition is specifically `i < 100`.

The statistical analysis is implemented properly. It provides useful information and results.

All additional tasks have been successfully completed. This deserves praise.

The launch commands do not meet the requirements in the specifications. However, your implementation may even be better.

The letter "Ґ" is missing from the Ukrainian alphabet.

Overall, the project works well and fulfils its core functions.

<img width="691" alt="image" src="https://github.com/OnDecember/Cryptograph/assets/116897595/37ac9723-5319-401c-8201-f0110574a5af">

**Comment by OnDecember** [comment]
Thanks for the constructive review.

**Comment by Y-Maxym** [comment]
Thanks for the constructive review.
